version: '3.7'

services:

  php:
    build: .docker/php
    volumes:
      - ./config/:/usr/src/blog/config
      - ./public:/usr/src/blog/public
      - ./src:/usr/src/blog/src
      - ./templates:/usr/src/blog/templates
      - ./var:/usr/src/blog/var
      - ./vendor:/usr/src/blog/vendor
    networks:
      - frontend
      - backend

  web:
    image: nginx
    volumes:
      - ./public:/usr/src/blog/public:ro
      - ./.docker/web/blog.conf:/etc/nginx/conf.d/blog.conf
    networks:
      - frontend
    ports:
      - 8081:80
    depends_on:
      - php

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    networks:
      - backend

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - frontend
      - backend

networks:
  frontend:
    name: frontend
  backend:
    name: backend
    internal: true